table segment
	lineageTag: d4e4b71c-2c35-41b9-8d7f-5db8085a6db7

	column Ticker
		dataType: string
		lineageTag: e8470ee0-94c8-4c99-9eaa-45d1a97c1422
		summarizeBy: none
		sourceColumn: Ticker

		annotation SummarizationSetBy = Automatic

	column Segmento
		dataType: string
		lineageTag: 56eb853c-7c04-4903-9980-50f854819cd2
		summarizeBy: none
		sourceColumn: Segmento

		annotation SummarizationSetBy = Automatic

	partition segment = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("bcxBCsIwEIXhu2TdS0yRVkInBBJbaugi1CARzUCpHq5bL2YbXRjj9uO93xgGeBSsYK2d3IXYUBhWln0KHeoUtGpgFbjPdKPZPz6KudV/TLS77a3dGOhKZ2+joqp0rgCyyZXLLVv5YMPo/PTOyj5OfxQhNy74iso+l5OLcBD7FABr8SXDCw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Ticker = _t, Segmento = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Ticker", type text}, {"Segmento", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

